/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: 'alumnos'}],
  whattodoSidebar: [{type: 'autogenerated', dirName: 'whattodo'}],
  directorioSidebar: [{type: 'autogenerated', dirName: 'directorio'}],
  //globalSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually

/*   tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ], */

  /* mentoresSidebar: [
    {
      type: 'category',
      label: 'Mentores',
      items: 'mentores/hola',
    }
  ] */
 /*  whattodoSidebar: [{type: 'autogenerated', dirName: '.'}], */
  //mentoresSidebar: [{type: 'doc', id: 'mentores', dirName: 'mentores'}],
  //globalSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually

/*   tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ], */

  /* mentoresSidebar: [
    {
      type: 'category',
      label: 'Mentores',
      items: 'mentores/hola',
    }
  ] */
};

export default sidebars;
